{
 "title": "app · demo-real",
 "tags": [
  "mini-cloud",
  "app",
  "demo-real"
 ],
 "panels": [
  {
   "title": "request rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=\"demo-real\"}[5m]))"
    }
   ]
  },
  {
   "title": "p95 latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=\"demo-real\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"demo-real\"}"
    }
   ]
  }
 ]
}